AllCops:
  Exclude:
    - 'tmp/'

Metrics/LineLength:
  Max: 120

Style/ExtraSpacing:
  Exclude:
    - metadata.rb
    - tmp/foodcritic/cookbook/metadata.rb

Style/SpaceBeforeFirstArg:
  Enabled: false
